$(document).ready( function(){


	$('#def-html').darkTooltip({
		opacity:1,
		gravity:'west'
	});
	$('#def-html1').darkTooltip({
		opacity:1,
		gravity:'west'
	});
	$('#def-html2').darkTooltip({
		opacity:1,
		gravity:'west'
	});
	$('#def-html3').darkTooltip({
		opacity:1,
		gravity:'west'
	});
	$('#def-html4').darkTooltip({
		opacity:1,
		gravity:'west'
	});
	$('#def-html5').darkTooltip({
		opacity:1,
		gravity:'west'
	});
	$('#def-html6').darkTooltip({
		opacity:1,
		gravity:'west'
	});
	$('#def-html7').darkTooltip({
		opacity:1,
		gravity:'west'
	});
	$('#def-html8').darkTooltip({
		opacity:1,
		gravity:'west'
	});
	$('#def-html9').darkTooltip({
		opacity:1,
		gravity:'west'
	});
	$('#def-html10').darkTooltip({
		opacity:1,
		gravity:'west'
	});
	$('#def-html11').darkTooltip({
		opacity:1,
		gravity:'west'
	});
	$('#def-html12').darkTooltip({
		opacity:1,
		gravity:'west'
	});
	$('#def-html13').darkTooltip({
		opacity:1,
		gravity:'west'
	});
	$('#def-html14').darkTooltip({
		opacity:1,
		gravity:'west'
	});
	$('#def-html15').darkTooltip({
		opacity:1,
		gravity:'west'
	});
	$('#def-html16').darkTooltip({
		opacity:1,
		gravity:'west'
	});
});
